version: 'build #{build}'

before_build:
  - set Path=C:\msys64\mingw64\bin;%Path%

build_script:
  - mkdir build
  - cd build
  - cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=C:\mingw64  -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
  - make
  - ctest --output-on-failure